[versions]
# 构建工具版本
# Android Gradle Plugin: https://developer.android.com/studio/releases/gradle-plugin
agp = "9.2.1"
# Kotlin 编译器: https://kotlinlang.org/docs/releases.html
# 注意: 需要和 hilt 版本对应
kotlin = "2.3.20"
# Android 核心库版本
# AndroidX Core KTX: https://developer.android.com/jetpack/androidx/releases/core
coreKtx = "1.19.0"
# 测试框架版本
# JUnit 4 测试框架: https://junit.org/junit4/
junit = "4.13.2"
# AndroidX JUnit 扩展: https://developer.android.com/jetpack/androidx/releases/test
junitVersion = "1.3.0"
# AndroidX Espresso 测试框架: https://developer.android.com/training/testing/espresso
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.14.0"
runner = "1.7.0"
compose = "1.11.4"
material3 = "1.4.0"

[libraries]
# Compose相关库
androidx-compose = { group = "androidx.compose.runtime", name = "runtime", version.ref = "compose" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }

# Android 核心库
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

# 测试相关库
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "runner" }

androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[plugins]
# Android 相关插件
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
